### ISSUE TITLE
profile picture

### ISSUE THREAD

**Issue by aval984** [omgmog/lightdm-webkit-google#13] opened 2016-07-01 07:47 UTC
for the life of me i could not get my profile picture to be displayed. i followed both of the methods listed but could not get it to work. finally i just went into the folder and replaced the stock avatar picture with my own.

**Comment by omgmog** [comment] 2016-07-01 08:15
Which distro are you running?

Having an image named `.face` (with no other extension) in `~` should be enough.

Failing that, you should be able to use the AccountsService. 

Edit/create the file `/var/lib/AccountsService/users/<username>`, and add the following lines:

```
[User]
Icon=/home/<username>/pathToYourPicture.png
```

If you go for the AccountsService method, make sure the image is readable by more than just your account.

**Comment by aval984** [comment] 2016-07-01 08:22
im running antergos. 
yea i did all that and couldnt get it to work for some reason.
idk maybe its just me.

**Comment by omgmog** [comment] 2016-07-01 08:25
Have you tried ensuring it's dimensions are `96x96` and it's readable by all?

**Comment by aval984** [comment] 2016-07-01 08:30
i didnt check the dimensions, but i did make it readable by all

**Comment by omgmog** [comment] 2016-07-01 08:32
Hmm I'm not sure what the cause could be then. It might be that Antergos is using `lightdm-webkit2-greeter`, which this theme isn't optimised for. 

I guess you've solved it by editing the theme, but you could also try setting `user_image` in the `[branding]` section of your `lightdm-webkit-greeter.conf`/`lightdm-webkit2-greeter.conf`.

**Comment by aval984** [comment] 2016-07-01 08:34
yes it is using webkit2. i didnt think about editing the greerer.conf file, but either way im happy with the results.

**Comment by omgmog** [comment] 2016-07-01 08:38
Alright cool, well I'll close this for now. Enjoy!

**Closed by omgmog** 2016-07-01 08:38 UTC
